2020-05-13T19:33:46,698 Non-user install because user site-packages disabled
2020-05-13T19:33:46,718 Created temporary directory: C:\Users\USER\AppData\Local\Temp\pip-ephem-wheel-cache-8hdk_f9f
2020-05-13T19:33:46,719 Created temporary directory: C:\Users\USER\AppData\Local\Temp\pip-req-tracker-6epxo82b
2020-05-13T19:33:46,719 Initialized build tracking at C:\Users\USER\AppData\Local\Temp\pip-req-tracker-6epxo82b
2020-05-13T19:33:46,719 Created build tracker: C:\Users\USER\AppData\Local\Temp\pip-req-tracker-6epxo82b
2020-05-13T19:33:46,719 Entered build tracker: C:\Users\USER\AppData\Local\Temp\pip-req-tracker-6epxo82b
2020-05-13T19:33:46,720 Created temporary directory: C:\Users\USER\AppData\Local\Temp\pip-install-z_4ahmn8
2020-05-13T19:33:46,737 1 location(s) to search for versions of pip-reviewpip-review:
2020-05-13T19:33:46,737 * https://pypi.org/simple/pip-reviewpip-review/
2020-05-13T19:33:46,737 Fetching project page and analyzing links: https://pypi.org/simple/pip-reviewpip-review/
2020-05-13T19:33:46,738 Getting page https://pypi.org/simple/pip-reviewpip-review/
2020-05-13T19:33:46,738 Found index url https://pypi.org/simple
2020-05-13T19:33:47,384 Could not fetch URL https://pypi.org/simple/pip-reviewpip-review/: 404 Client Error: Not Found for url: https://pypi.org/simple/pip-reviewpip-review/ - skipping
2020-05-13T19:33:47,385 Given no hashes to check 0 links for project 'pip-reviewpip-review': discarding no candidates
2020-05-13T19:33:47,385 ERROR: Could not find a version that satisfies the requirement pip-reviewpip-review (from versions: none)
2020-05-13T19:33:47,388 ERROR: No matching distribution found for pip-reviewpip-review
2020-05-13T19:33:47,389 Exception information:
2020-05-13T19:33:47,389 Traceback (most recent call last):
2020-05-13T19:33:47,389   File "c:\cyber\2020\rplace\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in _main
2020-05-13T19:33:47,389     status = self.run(options, args)
2020-05-13T19:33:47,389   File "c:\cyber\2020\rplace\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 185, in wrapper
2020-05-13T19:33:47,389     return func(self, options, args)
2020-05-13T19:33:47,389   File "c:\cyber\2020\rplace\venv\lib\site-packages\pip\_internal\commands\install.py", line 333, in run
2020-05-13T19:33:47,389     reqs, check_supported_wheels=not options.target_dir
2020-05-13T19:33:47,389   File "c:\cyber\2020\rplace\venv\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 179, in resolve
2020-05-13T19:33:47,389     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2020-05-13T19:33:47,389   File "c:\cyber\2020\rplace\venv\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 362, in _resolve_one
2020-05-13T19:33:47,389     abstract_dist = self._get_abstract_dist_for(req_to_install)
2020-05-13T19:33:47,389   File "c:\cyber\2020\rplace\venv\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 313, in _get_abstract_dist_for
2020-05-13T19:33:47,389     self._populate_link(req)
2020-05-13T19:33:47,389   File "c:\cyber\2020\rplace\venv\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 279, in _populate_link
2020-05-13T19:33:47,389     req.link = self.finder.find_requirement(req, upgrade)
2020-05-13T19:33:47,389   File "c:\cyber\2020\rplace\venv\lib\site-packages\pip\_internal\index\package_finder.py", line 930, in find_requirement
2020-05-13T19:33:47,389     req)
2020-05-13T19:33:47,389 pip._internal.exceptions.DistributionNotFound: No matching distribution found for pip-reviewpip-review
2020-05-13T19:33:47,430 Removed build tracker: 'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-req-tracker-6epxo82b'
